name: "Simple Greeting Action"   # Display name shown in GitHub UI
description: "A custom GitHub Action to print greeting message inputs"   # Purpose of this action

inputs:   # Inputs that workflow will pass into this action
  username:   # Input variable → accessed as inputs.username
    description: "Name of user to greet"   # Explains purpose of input
    required: true   # Mandatory → workflow fails if not provided

  season:   # Optional input variable
    description: "Name of Season"   # Explains purpose
    required: false   # Not mandatory
    default: "summer"   # Default value if not provided

outputs:   # Outputs returned from this action to workflow
  message:   # Output variable name → accessed as steps.<id>.outputs.message
    description: "Generated Greeting Message"   # Description of output
    value: ${{ steps.greet.outputs.message }}   # Maps output from step ID "greet"

runs:   # Defines execution behavior of action
  using: "composite"   # Composite action → runs multiple shell steps
  steps:   # Steps executed inside this action
    - name: Print Greeting   # Step name (visible in logs)
      id: greet   # IMPORTANT → required to reference outputs from this step
      shell: bash   # Shell used to run commands (bash for Linux runners)
      run: |   # Multi-line script block

        echo "Hello ${{ inputs.username }}, Welcome to ${{ inputs.season }} season."
        # Prints greeting message using input values

        echo "message=Hello ${{ inputs.username }}" >> $GITHUB_OUTPUT
        # Sets output variable
        # message → output key
        # Hello username → output value
        # >> $GITHUB_OUTPUT → writes to special GitHub file for outputs
